spring.application.name=skillexchange


# ========== CONFIG DE BASE ==========
server.port=8081

# ========== BASE DE DONNÉES H2 ==========
spring.datasource.url=jdbc:h2:mem:gamificationdbb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ========== JPA / HIBERNATE ==========
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ========== CONSOLE H2 ==========
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

##spring.config.import=configserver:
spring.mail.protocol=smtp
spring.mail.test-connection=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ayari2014khalil@gmail.com
spring.mail.password=korm xcbx etfp cgup
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


spring.cloud.config.enabled=false
spring.cloud.config.uri=http://localhost:8888


logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.commons.mail=DEBUG
